import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Sora } from "next/font/google";
import "./globals.css";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
	title: "Cine Rental | Learn with Sumit",
	description: "Generated by LWS",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="dark">
			<body
				className={`dark:bg-body bg-white ${sora.className} dark:text-white text-dark`}
			>
				<Header />
				<main>{children}</main>
				<Footer />
				<div id="movie-modal-content" />
			</body>
		</html>
	);
}
